
import Navbar from "@/components/navbar";
import Banner from "@/components/Banner";
import "./globals.css"
import Footer from "@/components/footer";
import 'bootstrap/dist/css/bootstrap.min.css';
export const metadata = {
  title: "FutbolFem",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <div className="grid grid-rows-[auto_auto_1fr_auto] min-h-dvh bg-black"> 
          <div><Navbar/></div>
          <div><Banner/></div>
          <main>{children}</main>
          <div><Footer/></div>
        
        </div>
      
      </body>
    </html>
  );
}
